In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
path = 'files'
files_names = os.listdir(path)

In [41]:
dfs = {} # dataframes dictionary

for file in files_names:
    df = pd.read_excel(f'./files/{file}')

    df['Proyecto'] = df.iloc[0,0] # crear una columna con el nombre del proyecto
    df = df.iloc[19:, [0,1,2,-1]] # eliminar las primeras filas y las columnas vacias
    df = df.drop(df.columns[1], axis=1) # elimina la columna intermedia con datos vacios
    df = df.dropna(axis=0, how='any') # quitar las filas que tengan datos vacios

    dfs[file] = df # Agregar el dataframe al diccionario

df_concat = pd.concat(dfs.values(), ignore_index=True) # Concatenar los dataframes

In [44]:
column_names = {'Unnamed: 0': 'cuenta', 'Unnamed: 2': 'Nombre_cuenta', 'Proyecto':'Proyecto'}
df_concat.rename(columns=column_names, inplace=True)
df_concat

,cuenta,Nombre_cuenta,Proyecto
0,1-0-00-000,ACTIVO,INMOBILIARIA VISTA SAN CRISTOBAL S.A.
1,1-1-00-000,ACTIVO CORRIENTES,INMOBILIARIA VISTA SAN CRISTOBAL S.A.
2,1-1-01-000,EFECTIVO Y EFECTIVO EQUIVALENTE,INMOBILIARIA VISTA SAN CRISTOBAL S.A.
3,1-1-01-001,CAJA CHICA,INMOBILIARIA VISTA SAN CRISTOBAL S.A.
4,1-1-01-002,FONDO FIJO,INMOBILIARIA VISTA SAN CRISTOBAL S.A.
...,...,...,...
5930,5-1-03-002,IMPUESTOS DIFERIDOS,INMOBILIARIA VISTA PENUELAS S.A.
5931,6-0-00-000,CUENTAS DE CUADRE,INMOBILIARIA VISTA PENUELAS S.A.
5932,6-1-00-000,CUENTAS DE CUADRE,INMOBILIARIA VISTA PENUELAS S.A.
5933,6-1-01-000,CUENTAS DE CUADRE,INMOBILIARIA VISTA PENUELAS S.A.
5934,6-1-01-001,CUENTAS DE CUADRE,INMOBILIARIA VISTA PENUELAS S.A.

In [45]:
df_concat.to_csv('all_data.csv', index=False)